<?php

namespace MyShop\DefaultBundle\Repository;

/**
 * OrdersProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersProductRepository extends \Doctrine\ORM\EntityRepository
{
}
