<?php

namespace MyShop\DefaultBundle\Repository;

use MyShop\DefaultBundle\Entity\Customer;
use MyShop\DefaultBundle\Entity\Orders;

/**
 * OrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOrCreateOrder(Customer $customer)
    {

        $manager = $this->getEntityManager();

        $dql = 'select o from MyShopDefaultBundle:Orders o where o.customer = :customer and o.status = :status';

        $order = $manager->createQuery($dql)->setParameters([
            'customer' => $customer,
            'status' => Orders::STATUS_OPEN
        ])->getOneOrNullResult();

        if ($order == null)
        {
            $order = new Orders();
            $customer->addOrder($order);
            $manager->persist($customer);
            $manager->flush();
        }

        $dateCreatedOrder = $order->getDateCreatedAt();

        $res = $dateCreatedOrder->diff(new \DateTime("now"));
        if ($res->h > 24) {
            $order->setStatus(Orders::STATUS_REJECT);
            $manager->persist($order);
            $manager->flush();
            $order = null;
        }

        return $order;
    }
}