services: 
    myshop_admin.check_img_type:  # имя сервиса
        class: MyShop\AdminBundle\Services\CheckImgType
        arguments:
            - "%upload_image_type_list%" # указание на конструктор

    myshop_admin.name_generator:  
        class: MyShop\AdminBundle\Services\NameGenerator

    myshop_admin.image_resize:  
        class: MyShop\AdminBundle\Services\Resizing

    myshop_admin.sending_mail:  
        class: MyShop\AdminBundle\Services\MailNotification
        arguments: 
             - "@mailer"
  
    myshop.product_photo_remover:
        class: MyShop\AdminBundle\Services\PhotoRemover
        arguments:
             - "@doctrine.orm.default_entity_manager"
             - "%image_root_dir%"

    myshop_admin.image_uploader:
        class: MyShop\AdminBundle\Services\UploadImageService
        arguments:
             - "@myshop_admin.check_img_type"
             - "@myshop_admin.name_generator"
        calls:
             - ["setUploadImageRootDir", ["%image_root_dir%"]]

    myshop_admin.product_import_export:
        class: MyShop\AdminBundle\Services\ProductImportExport
        arguments:
            - "@doctrine.orm.entity_manager"

             

             

